Add a problem with bounds and constraints
JuliaSmoothOptimizers/NLPModelsTest.jl pull request #38
Opened 2022-02-18 19:59 UTC by tmigot

I noticed in https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/50 that the coverage is decreasing because we don't have a problem with both bounds and constraints in the problem list.

https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/main/src/ADNLPProblems/hs13.jl

2022-02-19 16:50 UTC, dpo reviewed
HS13 is degenerate. Many solvers won't be able to solve it. What will it be used for?

2022-02-21 17:11 UTC, tmigot commented
We usually consider the problems from this package to test the NLPModel API, so we never try to solve them.
They are used in the following four packages only: `ADNLPModels`, `NLPModelsJuMP`, `CUTEst`, `AmplNLReader`.

2022-02-21 18:34 UTC, abelsiqueira requested changes
Thanks for the addition, it is good to have more coverage. I made some suggestions.

2022-02-21 18:34 UTC, abelsiqueira commented on src/NLPModelsTest.jl
> +  ["BROWNDEN", "HS5", "HS6", "HS10", "HS13", "HS11", "HS14", "LINCON", "LINSV", "MGH01Feas"]
```suggestion
  ["BROWNDEN", "HS5", "HS6", "HS10", "HS11", "HS13", "HS14", "LINCON", "LINSV", "MGH01Feas"]
```

2022-02-21 18:34 UTC, abelsiqueira commented on src/nlp/problems/hs13.jl
> +\\text{s. to} \\quad & 0 \\geq (1 - x_1)^3 - x_2
```suggestion
\\text{s. to} \\quad & (1 - x_1)^3 - x_2 \\geq 0
```

2022-02-21 18:34 UTC, abelsiqueira commented on src/nlp/problems/hs13.jl
> +    x0 = T[-2; 2],
```suggestion
    x0 = T[-2; -2],
```

2022-02-21 18:34 UTC, abelsiqueira commented on src/nlp/problems/hs13.jl
> +  cols[3] = 2
You don't need `nnzh = 3`. Mixed derivatives are 0. `hess_coord` should be fixed as well.

2022-02-21 18:34 UTC, abelsiqueira commented on src/nlp/problems/hs13.jl
> +  Jv .= [(-3 * (1 - x[1])^2) * v[1] - v[2]]
```suggestion
  Jv .= (-3 * (1 - x[1])^2) * v[1] - v[2]
```

2022-02-22 07:22 UTC, abelsiqueira approved these changes

2022-02-22 07:23 UTC, merged

2022-02-22 07:23 UTC, abelsiqueira commented
Thanks for the update